language: python
env:
  global:
  - secure: IrUGhi6wLNjZTcVmyvlUW4S8gvbsjd1KGTONBBFJLe2SsczfuTIp0UrwPYAu3O2mEh04ivdgpjy/sKKH+atd+mx1WGYpyc7telS+6pzzGhW+utLnknETJYN0diK1Th62GFDhbwtvjoLcn2VMT22Agh94Ob4JvD0tzlDcZpEOOEs=
  - secure: YV9GTtTddGgvvaW/o0esSY5ov8qIZJI77+mapAR138JrUi4opSXPzVk9XzHXCRR6K1IPBJ/PZfF+optX6SGWiD634A8T1vvrt8X/RrvV0Lbu3V33Qxi7UQgVRTGbR61RlzSEe1WjVXUKdZGMz+O07hwzS/MVkY88K48h/3Gtej8=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libatlas-dev libatlas-base-dev liblapack-dev libhdf5-serial-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended gfortran
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy scipy==0.15.1 matplotlib coverage cpp-coveralls
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout= buildout:newest=false
script:
- ./bin/python -c 'import pkg_resources; from bob.learn.boosting import get_config; print(get_config())'
- ./bin/coverage run --source=bob.learn.boosting ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
